apiVersion: v1
kind: ConfigMap
metadata:
 name: catalogue
 namespace: roboshop
 labels:
  project: roboshop
  tier: backend
  component: catalogue
data:
 MONGO: "true"
 MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: catalogue
 namespace: roboshop
 labels:
  project: roboshop
  tier: backend
  component: catalogue
spec:
 replicas: 1
 selector:
  matchLabels:
   project: roboshop
   tier: backend
   component: catalogue
 template:
  metadata:
   labels:
    project: roboshop
    tier: backend
    component: catalogue
  spec:
   containers:
    - name: catalogue
      image: sivamedam/catalogue:1.4.0
      imagePullPolicy: Always
      resources:
       requests:
        cpu: "100m"
        memory: "64Mi"
       limits:
        cpu: "200m"
        memory: "128Mi"
      readinessProbe:
       tcpSocket:
        port: 8080
       failureThreshold: 2 #If the readiness check fails 2 times in a row, Kubernetes marks the pod as Not Ready.
       periodSeconds: 10 #Kubernetes performs the readiness check every 10 seconds.
       initialDelaySeconds: 15 #After the container starts, Kubernetes waits 15 seconds before performing the first readiness check.
      livenessProbe:
       httpGet:
        path: /health
        port: 8080
       failureThreshold: 2 
       periodSeconds: 10  
      envFrom:
       - configMapRef:
          name: catalogue
---
apiVersion: v1
kind: Service
metadata:
 name: catalogue
 namespace: roboshop
 labels:
  project: roboshop
  tier: backend
  component: catalogue
spec:
 type: ClusterIP
 selector:
  project: roboshop
  tier: backend
  component: catalogue
 ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HarizontalPodAutoscaler
metadata:
 name: catalogue
 namespace: roboshop
spec:
 scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: catalogue
 minReplicas: 1
 maxReplicas: 10
 metrics:
  - type: Resource
    resource:
     name: cpu
     target:
      type: Utilization
      averageUtilization: 20
